spring.application.name=SpringBootJpaSecurity_5

# data source
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/jpa_security
spring.datasource.username=root
spring.datasource.password=1234

# session persistence
server.servlet.session.persistent=false

# jpa
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# spring security debug logging
logging.level.org.springframework.security=DEBUG